# Generated by Django 3.2.5 on 2021-07-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=50)),
                ('number', models.CharField(default='0000000000', max_length=10)),
                ('mail', models.EmailField(default='', max_length=254)),
                ('passwd', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
