# Generated by Django 3.2.5 on 2021-07-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='passwd',
            field=models.CharField(max_length=100),
        ),
    ]
