# Generated by Django 3.2.5 on 2021-07-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_auto_20210727_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hashid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
