# Generated by Django 3.2.5 on 2021-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_auto_20210727_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('reciever', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=10000)),
                ('isSeen', models.IntegerField(default=0)),
                ('isDeliver', models.IntegerField(default=0)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
        migrations.DeleteModel(
            name='Contects',
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='hashid',
            field=models.CharField(max_length=150),
        ),
    ]
