# Generated by Django 3.2.8 on 2021-10-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_auto_20211027_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(upload_to='static\\media'),
        ),
    ]
