# Generated by Django 3.2.8 on 2021-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_alter_users_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default='2021-11-07'),
        ),
    ]
