# Generated by Django 3.2.8 on 2021-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default='2021-11-22'),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
