# Generated by Django 3.2.8 on 2021-11-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0009_auto_20211122_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='users',
            name='hashid',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='users',
            name='passwd',
            field=models.CharField(max_length=512),
        ),
    ]
