# Generated by Django 3.2.8 on 2021-11-22 18:56

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_auto_20211122_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hashid',
            field=models.CharField(default='55153a32b41cd82be622198d7f9e6770', max_length=512),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default='2021-11-23'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=Chat.models.time),
        ),
    ]
