# Generated by Django 3.2.8 on 2021-11-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0011_auto_20211123_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashid',
            field=models.CharField(default='45c0aa3933d56e6aaf4a6e4d1f0d47ac', max_length=512),
        ),
    ]
